# Generated by Django 3.1 on 2020-12-16 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_auto_20201216_0322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='username',
        ),
        migrations.AlterField(
            model_name='contact',
            name='question',
            field=models.CharField(max_length=64),
        ),
    ]
